export const LOGIN_FETCH_PENDING = "LOGIN_FETCH_PENDING";
export const LOGIN_FETCH_SUCCESS = "LOGIN_FETCH_SUCCESS";
export const LOGIN_FETCH_FAILURE = "LOGIN_FETCH_FAILURE";

export const REGISTRATION_PENDING = "REGISTRATION_PENDING";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const REGISTRATION_FAILURE = "REGISTRATION_FAILURE";

export const EXAM_DETAILS_PENDING = "EXAM_DETAILS_PENDING";
export const EXAM_DETAILS_SUCCESS = "EXAM_DETAILS_SUCCESS";
export const EXAM_DETAILS_FAILURE = "EXAM_DETAILS_FAILURE";

export const EXAM_PAPER_PENDING = "EXAM_PAPER_PENDING";
export const EXAM_PAPER_SUCCESS = "EXAM_PAPER_SUCCESS";
export const EXAM_PAPER_FAILURE = "EXAM_PAPER_FAILURE";

export const VIEW_EXAM_PENDING = "VIEW_EXAM_PENDING";
export const VIEW_EXAM_SUCCESS = "VIEW_EXAM_SUCCESS";
export const VIEW_EXAM_FAILURE = "VIEW_EXAM_FAILURE";

export const DELETE_EXAM_PENDING = "DELETE_EXAM_PENDING";
export const DELETE_EXAM_SUCCESS = "DELETE_EXAM_SUCCESS";
export const DELETE_EXAM_FAILURE = "DELETE_EXAM_FAILURE";

export const ALL_STUDENT_PENDING = "ALL_STUDENT_PENDING";
export const ALL_STUDENT_SUCCESS = "ALL_STUDENT_SUCCESS";
export const ALL_STUDENT_FAILURE = "ALL_STUDENT_FAILURE";

export const VIEW_STUDENT_PENDING = "VIEW_STUDENT_PENDING";
export const VIEW_STUDENT_SUCCESS = "VIEW_STUDENT_SUCCESS";
export const VIEW_STUDENT_FAILURE = "VIEW_STUDENT_FAILURE";

export const STUDENT_EXAM_PENDING = "STUDENT_EXAM_PENDING";
export const STUDENT_EXAM_SUCCESS = "STUDENT_EXAM_SUCCESS";
export const STUDENT_EXAM_FAILURE = "STUDENT_EXAM_FAILURE";

export const FORGOT_PASSWORD_PENDING = "FORGOT_PASSWORD_PENDING";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD__SUCCESS";
export const FORGOT_PASSWORD_FAILURE = "FORGOT_PASSWORD_FAILURE";

export const NEW_PASSWORD_PENDING = "NEW_PASSWORD_PENDING";
export const NEW_PASSWORD_SUCCESS = "NEW_PASSWORD_SUCCESS";
export const NEW_PASSWORD_FAILURE = "NEW_PASSWORD_FAILURE";

export const RESET_PASSWORD_PENDING = "RESET_PASSWORD_PENDING";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILURE = "RESET_PASSWORD_FAILURE";
